#!/usr/bin/env bash

set -e

if [ "$#" -ne 3 ]; then
    echo "Usage: ./install <openrc> <tag> <ssh_key>"
    exit 1
fi

OPENRC_FILE="$1"
TAG="$2"
SSH_KEY="$3"

source scripts/common.sh

log "Starting deployment of $TAG using $OPENRC_FILE for credentials."

check_file_exists "$SSH_KEY" "SSH key file"
check_openstack_cli
load_openrc "$OPENRC_FILE"
check_openstack_connection

create_keypair_if_missing "$TAG" "$SSH_KEY"
create_network_if_missing "$TAG"
create_security_group_if_missing "$TAG"

log "Install basic OpenStack validation completed."
